import { EQUIPMENT, UNIVERSAL_TERMS, finePrintTable } from '@/lib/content';
import Reveal from './Reveal';
import SectionHeading from './SectionHeading';

/**
 * The honest fine-print grid. Rows are generated by finePrintTable() from the
 * same PLANS array the cards use, so the two can never disagree.
 *
 * Wide screens get a true comparison table; narrow screens get stacked
 * definition blocks, which keeps the layout readable down to 320px without a
 * horizontal scroll container.
 */
export default function FinePrintGrid() {
  const { plans, rows } = finePrintTable();

  return (
    <section
      id="fine-print"
      className="border-t border-mist-line bg-white px-5 py-16 sm:px-6 lg:px-8 lg:py-20"
    >
      <div className="mx-auto w-full max-w-6xl">
        <Reveal>
          <SectionHeading
            eyebrow="Pricing & fees"
            title="Complete pricing and fee disclosure"
            description="Monthly rates, equipment charges and plan inclusions, documented in full — every figure available to review before you place an order."
          />
        </Reveal>

        {/* ---------- Comparison table (lg and up) ---------- */}
        <Reveal>
          <div className="mt-11 hidden overflow-hidden rounded-[18px] shadow-[0_18px_44px_-30px_rgba(30,39,64,0.55)] ring-1 ring-mist-line lg:block">
            <table className="w-full border-collapse text-left">
              <caption className="sr-only">
                Plan rates, terms and inclusions compared
              </caption>
              <thead>
                <tr className="bg-navy">
                  <th
                    scope="col"
                    className="w-[17%] px-5 py-4.5 text-[0.75rem] sm:text-[0.6875rem] font-bold uppercase tracking-[0.14em] text-white/60"
                  >
                    Detail
                  </th>
                  {plans.map((plan) => (
                    <th
                      key={plan.id}
                      scope="col"
                      className={`border-l border-white/10 px-5 py-4.5 text-[0.9375rem] font-bold tracking-[-0.015em] ${
                        plan.isPopular ? 'text-sonic-bright' : 'text-white'
                      }`}
                    >
                      {plan.name}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {rows.map((row) => (
                  <tr
                    key={row.label}
                    className="align-top transition-colors duration-150 even:bg-mist/60 hover:bg-brand/[0.04]"
                  >
                    <th
                      scope="row"
                      className="border-b border-mist-line px-5 py-4 text-[0.8125rem] font-bold uppercase tracking-[0.06em] text-graphite"
                    >
                      {row.label}
                    </th>
                    {row.values.map((value, index) => (
                      <td
                        key={`${row.label}-${plans[index].id}`}
                        className={`border-b border-l border-mist-line px-5 py-4 text-[0.875rem] leading-relaxed ${
                          plans[index].isPopular
                            ? 'font-medium text-graphite-deep'
                            : 'text-graphite'
                        }`}
                      >
                        {value ?? <span className="text-graphite/45">&mdash;</span>}
                      </td>
                    ))}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Reveal>

        {/* ---------- Stacked cards (below lg) ---------- */}
        <div className="mt-11 grid gap-5 sm:grid-cols-2 lg:hidden">
          {plans.map((plan, planIndex) => (
            <Reveal key={plan.id} delay={planIndex * 70} className="h-full">
              <div
                className={`h-full rounded-[18px] bg-white p-5 sm:p-6 ${
                  plan.isPopular
                    ? 'ring-2 ring-brand/60'
                    : 'ring-1 ring-mist-line'
                }`}
              >
                <h3 className="text-[1.0625rem] font-bold leading-snug tracking-[-0.02em] text-graphite-deep">
                  {plan.name}
                </h3>
                <dl className="mt-4 space-y-3">
                  {rows.map((row) => {
                    const value = row.values[planIndex];
                    if (!value) return null;
                    return (
                      <div
                        key={`${plan.id}-${row.label}`}
                        className="grid grid-cols-[42%_1fr] gap-3"
                      >
                        <dt className="text-[0.8125rem] sm:text-[0.75rem] font-bold uppercase tracking-[0.05em] text-graphite">
                          {row.label}
                        </dt>
                        <dd className="text-[0.8125rem] leading-relaxed text-graphite-deep">
                          {value}
                        </dd>
                      </div>
                    );
                  })}
                </dl>
              </div>
            </Reveal>
          ))}
        </div>

        {/* ---------- Hardware + universal terms ---------- */}
        <div className="mt-6 grid gap-6 lg:grid-cols-2">
          <Reveal className="h-full">
            <div className="h-full rounded-[18px] bg-mist p-6 ring-1 ring-mist-line sm:p-7">
              <h3 className="text-[1.125rem] font-bold tracking-[-0.02em] text-graphite-deep">
                Optional WiFi hardware
              </h3>
              <p className="mt-2.5 text-[0.9375rem] leading-relaxed text-graphite">
                Renting a router is never required — supply your own if you prefer.
                Rentals include free replacements and automatic firmware updates.
              </p>
              <ul className="mt-6 divide-y divide-mist-line border-t border-mist-line">
                {EQUIPMENT.map((item) => (
                  <li
                    key={item.id}
                    className="flex items-start justify-between gap-4 py-4"
                  >
                    <div className="min-w-0">
                      <p className="text-[0.9375rem] font-bold text-graphite-deep">
                        {item.name}
                      </p>
                      <p className="mt-1 text-[0.8125rem] leading-relaxed text-graphite">
                        {item.detail}
                      </p>
                    </div>
                    <span className="shrink-0 text-[1rem] font-bold tabular-nums text-brand">
                      {item.monthly}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          </Reveal>

          <Reveal delay={80} className="h-full">
            <div className="h-full rounded-[18px] bg-mist p-6 ring-1 ring-mist-line sm:p-7">
              <h3 className="text-[1.125rem] font-bold tracking-[-0.02em] text-graphite-deep">
                Applies to every plan
              </h3>
              <p className="mt-2.5 text-[0.9375rem] leading-relaxed text-graphite">
                The charges customers normally have to search for, stated up front.
              </p>
              <dl className="mt-6 divide-y divide-mist-line border-t border-mist-line">
                {UNIVERSAL_TERMS.map((term) => (
                  <div
                    key={term.label}
                    className="flex items-start justify-between gap-4 py-4"
                  >
                    <dt className="min-w-0 text-[0.9375rem] text-graphite-deep">
                      {term.label}
                    </dt>
                    <dd className="shrink-0 text-right text-[0.9375rem] font-bold tabular-nums text-graphite-deep">
                      {term.value}
                    </dd>
                  </div>
                ))}
              </dl>
              <p className="mt-6 text-[0.8125rem] leading-relaxed text-graphite">
                Promotional rates apply to the first 12 months of service. Taxes and
                government fees are additional and vary by location. Current terms for
                your address are confirmed on the call before any order is placed.
              </p>
            </div>
          </Reveal>
        </div>
      </div>
    </section>
  );
}
